// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/chart/Bar.vue')['default']
    Donut: typeof import('./src/components/chart/donut.vue')['default']
    Dotplot: typeof import('./src/components/chart/dotplot.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Line: typeof import('./src/components/chart/Line.vue')['default']
    StackedHorizontalBar: typeof import('./src/components/chart/StackedHorizontalBar.vue')['default']
    Treemap: typeof import('./src/components/chart/treemap.vue')['default']
    Wrapper: typeof import('./src/components/chart/wrapper.vue')['default']
  }
}

export { }
